name: Autenticacion

on:
  workflow_call:
    secrets:  
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true


jobs:
  AWS-LOGIN:
    runs-on: ubuntu-24.04
    steps:
       - name: Autenticarse en AWS
         uses: aws-actions/configure-aws-credentials@v1
         env:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: us-east-1